### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for MultiGRU

### ISSUE THREAD

**Issue by kzfm** [Mishima-syk/13#1]
I got RuntimeError.

- python-3.6.8
- pytorch-1.0.0

```
$ ./main.py --scoring-function tanimoto --scoring-function-kwargs query_structure 'COc1ccccc1' --num-steps 10
Traceback (most recent call last):
  File "./main.py", line 59, in <module>
    train_agent(**arg_dict)
  File "/Users/kzfm/mishima_syk/REINVENT/train_agent.py", line 41, in train_agent
    Prior.rnn.load_state_dict(torch.load('data/Prior.ckpt', map_location=lambda storage, loc: storage))
  File "/Users/kzfm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultiGRU:
	size mismatch for gru_1.bias_ih: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1536]).
	size mismatch for gru_1.bias_hh: copying a param with shape torch.Size([1, 1536]) from checkpoint, the shape in current model is torch.Size([1536]).

```

**Comment by kzfm** [comment]
Resolved, my pytorch version was wrong.

`conda install pytorch=0.3.1 -c pytorch`

**Comment by meghanakaranam1** [comment]
> Resolved, my pytorch version was wrong.
> 
> `conda install pytorch=0.3.1 -c pytorch`

Can you please let me know, how to install version 0.3.1 in google colab?
